[INFO   ] Logger: Record log in /storage/emulated/0/Progamar/Webview/.kivy/logs/kivy_21-11-24_2.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  9 2021, 08:02:40) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.0 V@415.0 (GIT@d39f783, I79de86aa2c, 1591296226) (Date:06/04/20)'>
[INFO   ] GL: OpenGL vendor <b'Qualcomm'>
[INFO   ] GL: OpenGL renderer <b'Adreno (TM) 308'>
[INFO   ] GL: OpenGL parsed version: 3, 0
[INFO   ] GL: Texture max size <8192>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[WARNING] Base: Unknown <android> provider
[INFO   ] Base: Start application main loop
[INFO   ] GL: NPOT texture support is available
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/android/runnable.py", line 38, in run
[WARNING] stderr:     self.func(*self.args, **self.kwargs)
[WARNING] stderr:   File "/storage/emulated/0/Progamar/Webview/webview.py", line 99, in on_open
[WARNING] stderr:     webview = WebViewA(mActivity)
[WARNING] stderr:   File "jnius/jnius_export_class.pxi", line 270, in jnius.jnius.JavaClass.__init__
[WARNING] stderr:   File "jnius/jnius_export_class.pxi", line 370, in jnius.jnius.JavaClass.call_constructor
[WARNING] stderr:   File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
[WARNING] stderr: jnius.jnius.JavaException: JVM exception occurred: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process ru.iiec.pydroid3:kivy (pid 23116), lock owner ru.iiec.pydroid3 (pid 21231) java.lang.RuntimeException
[INFO   ] Base: Leaving application in progress...
